// my page
export const SET_USER_INFO = 'set_user_info'
export const LOG_OUT = 'log_out'
export const EDIT_NAME = 'edit_name'
export const SET_LOCATION = 'set_location'
export const SET_ADDRESS = 'set_address'

// home page
export const SHOW_LOADING = 'show_loading'
export const HIDE_LOADING = 'hiden_loading'
export const SELECT_ADDRESS = 'select_address'
export const SET_CITY_LIST = 'set_city_list'
export const SET_CURRENT_CITY = 'set_current_city'
export const SET_SWIPER_DATA = 'set_swiper_data'
export const REQ_RESTURANT = 'req_resturant'
export const REQ_FILTER_DATA = 'reqw_filter_data'
export const SET_TYPE_SELECT = 'set_type_select'
export const CLEAR_ALL_SELECT = 'clear_all_select'
export const CLEAR_ALL_RESTS = 'clear_all_rests'
export const SET_LAT_LNT = 'set_lat_lnt'
export const SET_DELIVER = 'set_deliver' 
export const SET_ACTIVITY = 'set_activity'
export const SET_CURRENT_SORT_TYPE = 'set_current_sort_type'
export const SET_CURRENT_OFFSET = 'set_current_offset'